package onl.fdt.android.fdtsdemo.ch6.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import onl.fdt.android.fdtsdemo.ch6.model.TodoListItem;

import onl.fdt.android.fdtsdemo.ch6.dao.TodoListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoListItemDaoConfig;

    private final TodoListItemDao todoListItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoListItemDaoConfig = daoConfigMap.get(TodoListItemDao.class).clone();
        todoListItemDaoConfig.initIdentityScope(type);

        todoListItemDao = new TodoListItemDao(todoListItemDaoConfig, this);

        registerDao(TodoListItem.class, todoListItemDao);
    }
    
    public void clear() {
        todoListItemDaoConfig.clearIdentityScope();
    }

    public TodoListItemDao getTodoListItemDao() {
        return todoListItemDao;
    }

}
